manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  defaults:
    remote: zephyrproject-rtos

  projects:
    - name: zephyr
      revision: 6072d4880d2d8deeadb506929adca4dba44c8220
      import: true

  self:
    path: esp-nmea-bridge
